image: node:alpine

stages:
  - install
  - build
  - test
  - deploy

install-client:
  stage: install
  script:
    - cd client
    - npm ci
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - client/node_modules/

install-server:
  stage: install
  script:
    - cd server
    - npm ci
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - server/node_modules/

build:
  stage: build
  dependencies: ["install-client"]
  script:
    - cd client
    - node --expose-gc --max-old-space-size=4096 node_modules/react-scripts/scripts/bundle.js
  artifacts:
    paths:
      - client/build/
    expire_in: 30 mins

unit-test-client:
  stage: test
  script:
    - cd client
    - echo "Executing unit tests..."
    - CI=true npm test -- --coverage
  needs: ["install-client"]
  dependencies:
    - install-client
  artifacts:
    name: "test-report"
    untracked: true
    exclude:
      - client/node_modules/**/*
    when: always
    expire_in: "1 day"

unit-test-server:
  stage: test
  script:
    - echo "Testing..."
    - sleep 1
    - echo "Done"
  needs: ["install-server"]
  dependencies:
    - install-server

integration-test:
  stage: test
  script:
    - echo "Testing..."
    - sleep 1
    - echo "Done"
  needs:
    ["install-server", "install-client"]
  dependencies:
    - install-client
    - install-server

system-test:
  stage: test
  script:
    - echo "Testing..."
    - sleep 1
    - echo "Done"
  needs:
    ["install-server", "install-client"]
  dependencies:
    - install-server
    - install-client

pre-deploy:
  stage: deploy
  script:
    - ls -la
    - cp -R ./client /var/www/team10-21-1/
    - cp -R ./server /var/www/team10-21-1/
    - cd /var/www/team10-21
    # - git stash
    # - git pull "https://team10-21:glpat--d6rb-Nhhb_srB2sMkDH@git-teaching.cs.bham.ac.uk/mod-team-project-2021/team10-21.git"
    - pm2 delete all

deploy-client:
  stage: deploy
  script:
    - cd /var/www/team10-21/client
    - npm ci
    - npm run build
    - pm2 serve -s build 3000 --spa
  needs: ["pre-deploy"]

deploy-server:
  stage: deploy
  script:
    - cd /var/www/team10-21/server
    - npm ci
    - pm2 start index.js
  needs: ["pre-deploy"]
