stages:
  - install
  - build
  - test
  - deploy

install-client:
  stage: install
  script:
    - cd client
    - echo "Installing client dependencies..."
    - npm ci
    - echo "Client dependencies installed successfully."
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - client/node_modules/

install-server:
  stage: install
  script:
    - cd server
    - echo "Installing server dependencies..."
    - npm ci
    - echo "Server dependencies installed successfully."
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - server/node_modules/

build:
  stage: build
  dependencies: ["install-client"]
  needs: ["install-client"]
  script:
    - cd client
    - echo "Building client for production..."
    - npm run build
    - echo "Client build created successfully."
  artifacts:
    paths:
      - client/build/
    expire_in: 30 mins

client-test:
  stage: test
  script:
    - cd client
    - echo "Executing unit and integration tests for client..."
    - CI=true npm test -- --coverage
    - echo "Client tests executed successfully."
  needs: ["install-client"]
  dependencies:
    - install-client
  artifacts:
    name: "test-report"
    untracked: true
    exclude:
      - client/node_modules/**/*
    when: always
    expire_in: 3 days

server-test:
  stage: test
  script:
    - cd server
    - echo "Executing unit and integration tests for server..."
    - npm test
    - echo "Server tests executed successfully."
  needs: ["install-server"]
  dependencies:
    - install-server
  artifacts:
    name: "test-report"
    untracked: true
    exclude:
      - server/node_modules/**/*
    when: always
    expire_in: 3 days

system-test:
  stage: test
  before_script:
    - cd server
    - pm2 start server.http.js
    - cd ../client
    - pm2 serve build 3001 --spa
  script:
    - echo "Executing system tests..."
    - CI=true npm run system-test
    - echo "System tests executed successfully."
  after_script:
    - pm2 delete server.http
    - pm2 delete static-page-server-3001
  needs:
    ["install-server", "install-client", "client-test", "server-test", "build"]
  dependencies:
    - install-server
    - install-client
    - build
  artifacts:
    name: "test-report"
    untracked: true
    exclude:
      - server/node_modules/**/*
      - client/node_modules/**/*
      - client/build/**/*
    when: always
    expire_in: 3 days

deploy-client:
  stage: deploy
  script:
    - echo "Deploying client..."
    - rsync -a --delete-after ./client/build/* $CLIENT_DEPLOY_LOCATION
    - echo "Client deployed successfully."

deploy-server:
  stage: deploy
  script:
    - echo "Deploying server..."
    - rsync -a --delete-after . $SERVER_DEPLOY_LOCATION
    - cd $SERVER_DEPLOY_LOCATION
    - cd server
    - pm2 restart server.js
    - echo "Server deployed successfully."
