stages:
  - install
  - build
  - test
  - deploy

install-client:
  stage: install
  script:
    - cd client
    - echo "Installing client dependencies..."
    - npm ci
    - echo "Client dependencies installed successfully."
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - client/node_modules/

install-server:
  stage: install
  script:
    - cd server
    - echo "Installing server dependencies..."
    - npm ci
    - echo "Server dependencies installed successfully."
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - server/node_modules/

build:
  stage: build
  dependencies: ["install-client"]
  needs: ["install-client"]
  script:
    - cd client
    - echo "Building client for production..."
    - npm run build
    - echo "Client build created successfully."
  artifacts:
    paths:
      - client/build/
    expire_in: 30 mins

client-test:
  stage: test
  script:
    - cd client
    - echo "Executing unit tests for client..."
    - CI=true npm test -- --coverage
    - echo "Client tests executed successfully."
  needs: ["install-client"]
  dependencies:
    - install-client
  artifacts:
    name: "test-report"
    untracked: true
    exclude:
      - client/node_modules/**/*
    when: always
    expire_in: 3 days

server-test:
  stage: test
  script:
    - cd server
    - echo "Executing unit tests for server..."
    - npm test
    - echo "Server tests executed successfully."
  needs: ["install-server"]
  dependencies:
    - install-server
  artifacts:
    name: "test-report"
    untracked: true
    exclude:
      - server/node_modules/**/*
    when: always
    expire_in: 3 days

system-test:
  stage: test
  script:
    - echo "Executing system tests..."
    - sleep 1
    - echo "System tests executed successfully."
  needs: ["install-server", "install-client", "client-test", "server-test"]
  dependencies:
    - install-server
    - install-client

deploy-client:
  stage: deploy
  script:
    - rsync -a --delete-after ./client/build/* /var/www/fresher-friend.bham.team/html/
    - cd /var/www/team10-21/
    - cd client

deploy-server:
  stage: deploy
  script:
    - rsync -a --delete-after . /var/www/team10-21/
    - cd /var/www/team10-21/server
    - pm2 restart server.js
