stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - cd client
    - npm install
    - cd ../server
    - npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - client/.npm
      - client/node_modules
      - server/node_modules

build:
  stage: build
  script:
    - cd client
    - npm run build
  artifacts:
    paths:
      - client/build/
    expire_in: 30 mins

unit-test-client:
  stage: test
  script:
    - cd client
    - echo "Executing unit tests..."
    - CI=true npm test -- --coverage
  needs: ["install"]
  dependencies:
    - install
  artifacts:
    name: "test-report"
    untracked: true
    exclude:
      - client/node_modules/**/*
    when: always
    expire_in: "1 day"

unit-test-server:
  stage: test
  script:
    - echo "Testing..."
    - sleep 1
    - echo "Done"
  needs: ["install"]
  dependencies:
    - install

integration-test:
  stage: test
  script:
    - echo "Testing..."
    - sleep 1
    - echo "Done"
  needs:
    ["install"]
  dependencies:
    - install

system-test:
  stage: test
  script:
    - echo "Testing..."
    - sleep 1
    - echo "Done"
  needs:
    ["install"]
  dependencies:
    - install

pre-deploy:
  stage: deploy
  script:
    - cd /var/www/team10-21
    - git stash
    - git pull "https://team10-21:glpat--d6rb-Nhhb_srB2sMkDH@git-teaching.cs.bham.ac.uk/mod-team-project-2021/team10-21.git"
    - pm2 delete all

deploy-client:
  stage: deploy
  dependencies:
    - install
    - build
  script:
    - cd /var/www/team10-21
    - cd client
    - npm ci
    - npm run build
    - pm2 serve -s build 3000 --spa
  needs: ["pre-deploy", "install", "build"]

deploy-server:
  stage: deploy
  dependencies:
    - install
  script:
    - cd /var/www/team10-21
    - cd server
    - pm2 start index.js
  needs: ["pre-deploy", "install"]
